# Docker 环境配置
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://mysql:3306/news?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true}
    username: ${SPRING_DATASOURCE_USERNAME:newsuser}
    password: ${SPRING_DATASOURCE_PASSWORD:newspassword}
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  # 生产环境优化配置
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  
  # 连接池配置
  hikari:
    maximum-pool-size: 20
    minimum-idle: 5
    connection-timeout: 30000
    idle-timeout: 600000
    max-lifetime: 1800000

# 日志配置
logging:
  level:
    com.News.cms: INFO
    org.springframework: WARN
    org.hibernate: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# 服务器配置
server:
  port: 8080
  servlet:
    context-path: /
